---
- name: Update apt
  apt: update_cache=yes

- name: Install requirements
  apt: name={{ item }} state=present
  with_items:
    - python-dev
    - libmysqlclient-dev
    # - python-mysqldb # Alternative if `libmysqlclient-dev` doesn't work
    - python-pip
    - python-virtualenv
