---
- hosts: all
  user: vagrant
  roles:
    - webserver
    - {role: mysql, mysql_db: [{name: flask_sandbox_db}], mysql_users: [{name: flask_sandbox, pass: flask_sandbox, priv: "*.*:ALL"}]}
    - redis
